on:
  pull_request:
    branches:
      - main
name: terraform-quality
jobs:
  encryption:
    uses: padok-team/github-workflows/.github/workflows/terraform-quality.yml@v1
    with:
      workdir: modules/encryption
  mysql:
    uses: padok-team/github-workflows/.github/workflows/terraform-quality.yml@v1
    with:
      workdir: modules/mysql
  postgresql:
    uses: padok-team/github-workflows/.github/workflows/terraform-quality.yml@v1
    with:
      workdir: modules/postgresql
  secrets:
    uses: padok-team/github-workflows/.github/workflows/terraform-quality.yml@v1
    with:
      workdir: modules/secrets
  sql-exporter:
    uses: padok-team/github-workflows/.github/workflows/terraform-quality.yml@v1
    with:
      workdir: modules/sql-exporter
