on:
  pull_request:
    branches:
      - main
name: terraform-quality
jobs:
  terraform-quality-encryption:
    uses: padok-team/github-workflows/.github/workflows/terraform-quality.yml@v1
    with:
      workdir: modules/encryption
  terraform-quality-mysql:
    uses: padok-team/github-workflows/.github/workflows/terraform-quality.yml@v1
    with:
      workdir: modules/mysql
  terraform-quality-postgresql:
    uses: padok-team/github-workflows/.github/workflows/terraform-quality.yml@v1
    with:
      workdir: modules/postgresql
  terraform-quality-secrets:
    uses: padok-team/github-workflows/.github/workflows/terraform-quality.yml@v1
    with:
      workdir: modules/secrets
  terraform-quality-sql-exporter:
    uses: padok-team/github-workflows/.github/workflows/terraform-quality.yml@v1
    with:
      workdir: modules/sql-exporter
